### ISSUE TITLE
Apply-PnPTenantTemplate : Value cannot be null. Parameter name: value

### ISSUE THREAD

**Issue by Chimosh** [pnp/sp-starter-kit#312] opened 2019-08-07 01:59 UTC
#### Category
- [ ] Question
- [ x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Running command
Apply-PnPTenantTemplate -Path .\starterkit.pnp

Results in an error I cannot find a solution for.
#### Observed Behavior

Apply-PnPProvisioningHierarchy : Value cannot be null.
Parameter name: value
At line:1 char:1
+ Apply-PnPProvisioningHierarchy -Path starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Apply-PnPTenantTemplate], ArgumentNullException
    + FullyQualifiedErrorId : System.ArgumentNullException,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.Apply
   TenantTemplate

#### Steps to Reproduce

Following instructions to install Sp starter kit 
https://github.com/SharePoint/sp-starter-kit

**Comment by AkashSonare** [comment] 2019-09-13 07:27
Facing same issue
Apply-PnPTenantTemplate : Object reference not set to an instance of an object.
At line:1 char:1
+ Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"PORTALURL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

**Comment by mkhoruzhiy** [comment] 2019-10-08 10:35
Hi Chimosh,

to your error "Apply-PnPProvisioningHierarchy : Value cannot be null." - I have had nearly the same one and found a solution. Maybe your case is similar but my error was
`**Apply-PnPTenantTemplate** : Value cannot be null.`

The problem for me was that I had a previous version sharepoint-starter-kit app installed in my App Catalog. It was installed by the starter kit some months ago but I didn't proceed at that time due to errors, then I had a long break and then tried again. So the starter kit installed the latest version package sharepoint-starter-kit while the old one was still in the catalog. It resulted in the "Value cannot be null" error.
I removed both packages, the old and the new one, and then ran the deployment again by the command:
Apply-PnPTenantTemplate -Path starterkit.pnp
That time, the process ran without errors.

**Comment by eoverfield** [comment] 2020-01-13 22:17
This appears to be a duplicate of: https://github.com/SharePoint/sp-starter-kit/issues/274

**Comment by bcameron1231** [comment] 2020-05-13 16:25
Closing this issue as it is duplicate, and has been inactive for a few months. If still have issues, please see if #274 is similar to your issue, if not, please open a new ticket.

**Closed by bcameron1231** 2020-05-13 16:25 UTC
Labels: status:duplicate
