### ISSUE TITLE
Portal Footer: My Links Dialog Disappears Once Expanded (Not All Users) 

### ISSUE THREAD

**Issue by Zerviak** [pnp/sp-starter-kit#303] opened 2019-07-15 21:20 UTC
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

When the user selects Edit in the Portal Footer, the My Links dialog box should stay open for the user to add their own links. The box appears small and then (seems to be by design) expands to show the options available to users for adding their own links to the footer. 

#### Observed Behavior

For most of the users, clicking on Edit within the Portal Footer makes a small rendered version of the My Links pop up to appear. After a second, instead of expanding, the box disappears and the site stays greyed out. The user then needs to refresh the site. This does not happen to the user who add the footer. 

#### Steps to Reproduce

1. Provision the starter kit
2. Apply the custom site design to the active modern site
3. Have another user try to Edit and add their 'My Links'. 

This may be a bug but I think I have something set up wrong. Do my users need special permissions to use the custom user profile properties I've set up for them? What may be causing this issue for them?

**Comment by bcameron1231** [comment] 2019-07-22 15:05
When you created the custom user profile property, did you make sure to give the user permission to edit the values for the property?"

I can't repro yet, but this is just a first guess.

**Comment by Zerviak** [comment] 2019-07-22 20:40
I follow the instructions for creating a custom user profile, including checking off the box for 'Allow users to edit values for this property'. Is there anything else within the User Profile Property section, permission based, I may have missed?

**Comment by bcameron1231** [comment] 2019-07-24 13:47
Nope, there isn't anything you would need to change aside from that check box. Is this happening in all browsers?

**Comment by Zerviak** [comment] 2019-07-25 14:50
It is and all users besides me. Interesting thing though: 

When we first implemented the footer, me and my other admin were able to use this feature. We then discovered that it was not working for other users so as part of my troubleshooting, I removed the custom profile and re-created it. Now he is unable to use My Links but I can. What looks to be happening is the pop up for My Links disappears when it expands. The entire screen is grayed out as if it is there but the pop up is invisible.

**Comment by bcameron1231** [comment] 2019-07-25 16:04
Can you open up Dev Tools in Chrome (F12) and then click the quick links and see if an error pops up for your other admins?

**Comment by Zerviak** [comment] 2019-07-26 16:29
Here is the error we get:

_sp-pages-assembly_en-us_5c471fe29dde54003a64b536019ac3d3.js:83 TypeError: Cannot read property 'length' of undefined
    at e.setItems (portal-footer-application-customizer_d937b4539658b49e336100183ac9e310.js:15)
    at new t (portal-footer-application-customizer_d937b4539658b49e336100183ac9e310.js:15)
    at ul (sp-pages-assembly_en-us_5c471fe29dde54003a64b536019ac3d3.js:83)
    at Pi (sp-pages-assembly_en-us_5c471fe29dde54003a64b536019ac3d3.js:83)
    at Ii (sp-pages-assembly_en-us_5c471fe29dde54003a64b536019ac3d3.js:83)
    at Qa (sp-pages-assembly_en-us_5c471fe29dde54003a64b536019ac3d3.js:83)
    at Ka (sp-pages-assembly_en-us_5c471fe29dde54003a64b536019ac3d3.js:83)
    at Oo (sp-pages-assembly_en-us_5c471fe29dde54003a64b536019ac3d3.js:83)
    at Po (sp-pages-assembly_en-us_5c471fe29dde54003a64b536019ac3d3.js:83)
    at To (sp-pages-assembly_en-us_5c471fe29dde54003a64b536019ac3d3.js:83)_

**Comment by eoverfield** [comment] 2019-07-26 17:48
@Zerviak is error is liking being thrown in PortalFooterApplicationCustomizer.ts, or the service, SPUserProfileService.ts, either when the user profile property is being queried, or when the results are processed. Difficult to tell.

In chrome dev tools, click on the line in the error:
at e.setItems (portal-footer-application-customizer_d937b4539658b49e336100183ac9e310.js:15)

Then format the JS so you get can more context as to where this particular line is coming from in the source. Likely right after that is a call to one of the responses.

In the code, it does look to me as there is proper error handling, but when you get an error on a property not readable on an undefined object, there must be an use-case that is not being handled.

**Comment by hturbano** [comment] 2019-10-09 15:14
@Zerviak 
Have you had any luck with this? We recently added the Portal Footer and are experiencing the same exact issue and error. Would love to know if you have figured out what the issue was. Looking forward to hearing from you and hoping you found a solution!

**Comment by bcameron1231** [comment] 2020-11-13 00:39
Looks like we still can't reproduce the issue. As this is over a year old, I am going to close this ticket. But if you have any more information to provide, please open a new support ticket! Thanks!

**Closed by bcameron1231** 2020-11-13 00:39 UTC
Labels: Needs: Triage :mag:, Version:V1
