### ISSUE TITLE
The user or administrator has not consented to use the application with ID '31359c7f-bd7e-475c-86db-fdb8c937548e' named 'PnP Management Shell'. Send an interactive authorization request for this user and resource.

### ISSUE THREAD

**Issue by LarsD83** [pnp/sp-starter-kit#436] opened 2020-09-09 13:12 UTC
## Category

- [x] Question

## Question

Unable to install Sharepoint Starter Kit:

I'm able to connect to my Sharepoint with an admin account via:  connect-PnPOnline https://manaiaconsulting.sharepoint.com/

Next step: Apply-PnPTenantTemplate -Path starterkit.pnp 

Error:
The user or administrator has not consented to use the application with ID
'31359c7f-bd7e-475c-86db-fdb8c937548e' named 'PnP Management Shell'. Send an interactive authorization request for
this user and resource.

Any Idea how to solve it?

Kind regards
Lars

**Comment by rjcg916** [comment] 2020-09-10 18:58
I am experiencing this same issue.

**Comment by gjerm** [comment] 2020-09-11 14:23
Also experiencing this issue.

**Comment by bcameron1231** [comment] 2020-09-11 14:39
Hi Everyone, can you confirm how you are connecting to SharePoint Online in PowerShell? Sounds like you may be using App only credentials and passing a ClientID?

**Comment by gjerm** [comment] 2020-09-11 14:43
I'm connecting using 

`Connect-PnPOnline -Url "https://tenant-admin.sharepoint.com/"`

With a regular user account (global admin with MFA disabled)

**Comment by rjcg916** [comment] 2020-09-11 16:24
connecting with sharepoint admin account non MFA 

Sent from AT&T Yahoo Mail on Android 
 
  On Fri, Sep 11, 2020 at 7:44 AM, Gjermund<notifications@github.com> wrote:   


I'm connecting using

Connect-PnPOnline -Url "https://tenant-admin.sharepoint.com/"

With a regular user account (global admin with MFA disabled)

**Comment by miloszpecyna** [comment] 2020-09-14 10:21
I have the same error message when I try to install Sharepoint Starter Kit.

**Comment by mhankosky** [comment] 2020-09-14 14:13
Having the same issue running this command : 

`#Parameter
$SiteURL= "https://name.sharepoint.com/sites/PN1004"
 
#Connect to PnP Online
Connect-PnPOnline -Url $SiteURL -Credentials (Get-Credential)
 
#Set Sharing Settings to Enable Anonymous sharing
Set-PnPTenantSite -Url $SiteURL -Sharing ExternalUserAndGuestSharing`

**Comment by eoverfield** [comment] 2020-09-14 16:28
What version of PnP PS are you using? Could you try to downgrade / upgrade to:

3.23.2007.1

**Comment by rjcg916** [comment] 2020-09-14 17:11
I created a brand new Tenant and got the same message.  I then downgraded PnP PowerShell to 3.20.2004.0, re-ran, and it worked.

**Comment by eoverfield** [comment] 2020-09-14 17:37
I opened up an issue over at PnP Core as well as this appears to be an issue with how the core engine provisions.

https://github.com/pnp/PnP-Sites-Core/issues/2757

**Comment by PaoloPia** [comment] 2020-09-18 15:31
Hi,
Thanks for using PnP. In order to apply the template, you need to have the PnP Management Shell app properly configured in your target tenant. We are working on releasing a new cmdlet in PnP PowerShell to ease and speed up the registration process. In the meantime, if you like, you can follow these steps (just the very first time):

_Connect-PnPOnline -Url "https://<tenant>.sharepoint.com/" -PnPManagementShell_

Follow the instructions, make the device login, and consent the SharePoint Online permission requests.

_Disconnect-PnPOnline
Connect-PnPOnline -Graph_

Follow the instructions, make the device login again, and consent the Microsoft Graph permission requests.

_Disconnect-PnPOnline_

Once you have done that, you can follow the "regular" provisioning path:

_Connect-PnPOnline -Url "https://<tenant>.sharepoint.com/"
Apply-PnPTenantTemplate -Path .\starterkit.pnp_

I will close this issue, but feel free to open another one in case of any further need. Thanks.

**Closed by PaoloPia** 2020-09-18 15:31 UTC
Labels: Environment:SharePoint Online, Needs: Author Feedback, Version:V2

**Comment by holylander** [comment] 2020-11-17 16:33
You just may need to [grant enough access rights (click here for details) to the `managment shell`](https://www.c-sharpcorner.com/article/implement-cicd-with-office-365-cli-for-spfx-solution-for-ms-teams/).
Take into account that `o365 CLI` has been replaced with `m365 CLI`

**Comment by RS-GHub** [comment] 2021-01-14 13:52
Hi @PaoloPia ,
Thanks for the workaround the bug.
But i think I found another bug (or human error which cannot ne corrected).

I have followed the first part:
"Connect-PnPOnline -Url "https://.sharepoint.com/" -PnPManagementShell

Follow the instructions, make the device login, and consent the SharePoint Online permission requests."

I gave consent to the permissions, but DID NOT click on "Give consent for the Organisation".
I was successfully connected to PnPOnline and the cursor in PowerShell console moved to cursor after the sign in guide and code...

Successfully disconnected and run next command:
"Connect-PnPOnline -Graph"

PS console came with the code again and I entered it on the site for the same account (mine)...
But then it came with this box (attached screenshot)
![Error connecting to -Graph](https://user-images.githubusercontent.com/55391170/104597678-85bb4a00-566d-11eb-8dde-13ffeca7177d.png)

More details:
"Troubleshooting details
If you contact your administrator, send this info to them.
Copy info to clipboard
Request Id: c0a11db2-4438-4caf-ad0f-2e0113173a00
Correlation Id: 9cc7efc8-f351-4205-965a-a1879ec2f348
Timestamp: 2021-01-14T13:50:49.868Z
App name: PnP Management Shell
App ID: 31359c7f-bd7e-475c-86db-fdb8c937548e
IP address: 80.0.111.19
Device identifier: a9159865-991b-40c4-a334-6d5c7e6e1fd5
Device platform: Windows 10
Device state: DomainJoined
Advanced diagnostics: Enable
If you plan on getting support for an issue, turn this on and try to reproduce the error. This will collect additional information that will help to troubleshoot the issue.

And when clicking OK, the same box reappears again and again in a loop.
And the console will not progress to the cursor as with the first consent above.
If I run "Disconnect-PnPOnline" on another console it comes with error "Disconnect-PnPOnline : No connection to disconnect"

I think possibly because I did not consent for the whole organisation in the first step.
But cannot find a way to log out and rerun the first consent in order to select "Give consent for the Organisation" as well.

I suppose that might be another bug and possibly @PaoloPia 's instruction need to specify that a consent should be given for organisation as well or resolve the issue with a way to go back to that screen and give organisational consent.

Meanwhile can someone let me know how to revert my PnP Management Shell app settings and start again.
As it stands now - once i went through the first part of consent - I cannot go back and include consent for my organisation.. if that is the problem for the Graph part.

Please let me know if you need more info on the error:

Thanks

RS

**Comment by Tyler-H** [comment] 2021-01-27 18:48
> 
> 
> Hi,
> Thanks for using PnP. In order to apply the template, you need to have the PnP Management Shell app properly configured in your target tenant. We are working on releasing a new cmdlet in PnP PowerShell to ease and speed up the registration process. In the meantime, if you like, you can follow these steps (just the very first time):
> 
> _Connect-PnPOnline -Url "https://.sharepoint.com/" -PnPManagementShell_
> 
> Follow the instructions, make the device login, and consent the SharePoint Online permission requests.
> 
> _Disconnect-PnPOnline Connect-PnPOnline -Graph_
> 
> Follow the instructions, make the device login again, and consent the Microsoft Graph permission requests.
> 
> _Disconnect-PnPOnline_
> 
> Once you have done that, you can follow the "regular" provisioning path:
> 
> _Connect-PnPOnline -Url "https://.sharepoint.com/" Apply-PnPTenantTemplate -Path .\starterkit.pnp_
> 
> I will close this issue, but feel free to open another one in case of any further need. Thanks.

It is worth noting that to do this you need to have the "Application Admin" role assigned to your account. Many people using this (like me) may not have that role assigned to them in their organization.

**Comment by somesh-bhalerao** [comment] 2021-06-08 08:47
SharePoint Online Management Shell and PnP.Pwershell can not go together. If want to execute PnP.PowerShell then must need to uninstall SharePoint Online Management Shell and restart the PC.
My issue is solved just by uninstalling SharePoint Online Management Shell.
PnP.PowerShell 1.6.0
SharePointPnPPowerShellOnline 3.29.2101.0

**Comment by eoverfield** [comment] 2021-06-08 20:43
@somesh-bhalerao I apologize for the errors you ran into, you should be able to run SPO PS and PnP.PS at the same time. This sounds more like an issue with PnP.PS you may want to report at https://github.com/pnp/PnP-PowerShell/issues
